exercise_configs:
  push_up:
    waterline: .4
    min_valley_length: 10
    max_valley_length: 50
    min_volume: 7
    max_volume: 187

  squat:
    waterline: 0.9
    min_valley_length: 25
    max_valley_length: 45
    min_volume: 20
    max_volume: 40