exercise_configs:
  push_up:
    waterline: .9
    min_valley_length: 10
    max_valley_length: 50
    min_volume: 7
    max_volume: 187

  squat:
    waterline: 0.0
    min_valley_length: 10
    max_valley_length: 45
    min_volume: 7
    max_volume: 47